Test tfdocs

diff --git a/.github/workflows/Preview_Plan.yaml b/.github/workflows/Preview_Plan.yaml
--- a/.github/workflows/Preview_Plan.yaml
+++ b/.github/workflows/Preview_Plan.yaml
@@ -1,10 +1,8 @@
 name: Terraform Preview
 
 on:
-  workflow_dispatch:
-  push:
-    branches:
-    - feature/*
+  pull_request:
+
 env:
   AWS_REGION: us-east-1
   TF_WORKSPACE: dev
@@ -38,32 +36,25 @@ jobs:
       uses: actions/cache@v4
       with:
         path: .terraform.d/plugin-cache
-        key: terraform-plugin-cache-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
+        key: terraform-plugin-cache-${{ runner.os }}-${{ hashFiles('**/*.tf')
+          }}
         restore-keys: |
-            terraform-plugin-cache-${{ runner.os }}-
+          terraform-plugin-cache-${{ runner.os }}-
 
-    - name: Install Terramate
-      uses: terramate-io/terramate-action@v2
+    - name: Setup Tools
+    - uses: asdf-vm/actions/setup@v4
       with:
-        version: 0.13.0
+        tool-versions-file: .tool-versions
+#        add-latest: true
 
-    - name: Install Terraform
-      uses: hashicorp/setup-terraform@v3
-      with:
-        terraform_version: 1.12.1
-        terraform_wrapper: false
-
-#    - name: Create Terraform Plugin Cache Dir
-#      run: |
-#        mkdir --parents ${{ env.TF_PLUGIN_CACHE_DIR }}
-#
-#    - name: Cache Terraform
-#      uses: actions/cache@v2
-#      with:
-#        path: ${{ env.TF_PLUGIN_CACHE_DIR }}
-#        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
-#        restore-keys: |
-#          ${{ runner.os }}-terraform-
+    - name: Check Terraform formatting
+      run: terraform fmt -recursive -check -diff
+      continue-on-error: true
+      env:
+        TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
+        TF_IN_AUTOMATION: true
+        TF_INPUT: false
+        TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
 
     - name: List changed stacks
       id: list
@@ -86,6 +77,9 @@ jobs:
           terraform init -lock-timeout=5m
       env:
         TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
+        TF_IN_AUTOMATION: true
+        TF_INPUT: false
+        TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
 
     - name: Validate Terraform configuration in changed stacks
       if: steps.list.outputs.stdout
@@ -94,8 +88,6 @@ jobs:
         terramate run \
           --parallel 5 \
           --changed \
-          --mock-on-fail \
-          --enable-sharing \
           -- \
           terraform validate
 
@@ -112,12 +104,52 @@ jobs:
           -- \
           terraform plan -out out.tfplan -lock=false
 
-    - name: Apply Terraform changes stacks
-      if: steps.plan.outcome == 'success'
+    - name: Generate preview details
+      if: steps.list.outputs.stdout
+      id: comment
       run: |
-        terramate run \
-          --parallel 5 \
-          --changed \
-          --enable-sharing \
-          --mock-on-fail \
-          -- terraform apply -auto-approve
+        echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
+        echo >>pr-comment.txt
+        echo >>pr-comment.txt "### Changed Stacks"
+        echo >>pr-comment.txt
+        echo >>pr-comment.txt '```bash'
+        echo >>pr-comment.txt "${{ steps.list.outputs.stdout }}"
+        echo >>pr-comment.txt '```'
+        echo >>pr-comment.txt
+        echo >>pr-comment.txt "#### Terraform Plan"
+        echo >>pr-comment.txt
+        echo >>pr-comment.txt '```terraform'
+        terramate run --changed -- terraform show -no-color out.tfplan |& dd bs=1024 count=248 >>pr-comment.txt
+        [ "${PIPESTATUS[0]}" == "141" ] && sed -i 's/#### Terraform Plan/#### :warning: Terraform Plan truncated: please check console output :warning:/' pr-comment.txt
+        echo >>pr-comment.txt '```'
+        cat pr-comment.txt >>$GITHUB_STEP_SUMMARY
+
+    - name: Generate preview when no stacks changed
+      if: success() && !steps.list.outputs.stdout
+      run: |
+        echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
+        echo >>pr-comment.txt
+        echo >>pr-comment.txt "### Changed Stacks"
+        echo >>pr-comment.txt
+        echo >>pr-comment.txt 'No changed stacks, no detailed preview will be generated.'
+        cat pr-comment.txt >>$GITHUB_STEP_SUMMARY
+
+    - name: Generate preview when things failed
+      if: always() && failure()
+      run: |
+        echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
+        echo >>pr-comment.txt
+        echo >>pr-comment.txt "### Changed Stacks"
+        echo >>pr-comment.txt
+        echo >>pr-comment.txt '```bash'
+        echo >>pr-comment.txt "${{ steps.list.outputs.stdout }}"
+        echo >>pr-comment.txt '```'
+        echo >>pr-comment.txt ':boom: Generating preview failed. Please see details in Actions output.'
+        cat pr-comment.txt >>$GITHUB_STEP_SUMMARY
+
+    - name: Publish generated preview as GitHub commnent
+      uses: marocchino/sticky-pull-request-comment@v2
+      with:
+        header: preview
+        path: pr-comment.txt
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
